diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=D:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
init.defaultbranch=master
user.email=asadthegift.ak@gmail.com
user.name=Asad
core.symlinks=false
core.repositoryformatversion=0
core.filemode=false
core.logallrefupdates=true
core.bare=false
remote.origin.url=https://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@https://github.com/afzal-mohammed/MyAutomation.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
